name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rake:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [
          'ruby-head',
          '3.4',
          '3.3'
        ]

    steps:
      - name: Set Share Env
        if: github.ref_name == 'main'
        run: |
          echo "SHARE=1" >> $GITHUB_ENV
          echo "CI=1" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run benchmarks
        run: bundle exec rake
      - name: Generate HTML files for each benchmark
        run: |
          for v in $(ls reports); do
            mkdir -p html_reports/$v
            for f in $(ls reports/$v/*.txt); do
              ruby scripts/generate_benchmarks_html.rb "$f" "html_reports/$v/$(basename $f .txt).html"
            done
          done
      - name: Upload HTML reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: html_reports/**/*

  publish:
    needs: rake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download HTML reports
        uses: actions/download-artifact@v4
        with:
          name: html-reports
          path: all_html_reports
      - name: Merge all HTML files into one
        run: |
          ruby scripts/merge_html_reports.rb all_html_reports merged_benchmarks.html
          touch .nojekyll
      - name: Prepare gh-pages branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf *
          cp merged_benchmarks.html ./
          touch .nojekyll
      - name: Commit and push merged HTML page
        run: |
          git add .
          git commit -m "Update merged benchmark HTML [ci skip]" || echo "No changes to commit"
          git push origin gh-pages
