name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rake:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [
          'ruby-head',
          '3.4',
          '3.3'
        ]

    steps:
      - name: Set Share Env
        if: github.ref_name == 'main'
        run: |
          echo "SHARE=1" >> $GITHUB_ENV
          echo "CI=1" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run benchmarks
        run: bundle exec rake
      - name: Generate HTML page for all versions
        run: bundle exec rake generate_versions_html

  publish:
    needs: rake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Copy generated HTML page
        run: |
          cp all_versions_benchmarks.html ./
          touch .nojekyll
      - name: Prepare gh-pages branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf *
          cp all_versions_benchmarks.html ./
          touch .nojekyll
      - name: Commit and push HTML page
        run: |
          git add .
          git commit -m "Update all versions benchmark HTML [ci skip]" || echo "No changes to commit"
          git push origin gh-pages
